server:
    port: 8080
spring:
    application:
        name: NEUCourseWiki
    data:
        mongodb:
            database: neu_course_wiki_db
            authentication-database: admin
            uri:mongodb://root:root@0.0.0.0:27017
